services:
  - type: web
    name: hirebase-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production

  - type: worker
    name: hirebase-worker
    runtime: docker
    plan: free # Note: Render free worker terbatas, jika gagal gabung ke web service
    dockerfilePath: ./Dockerfile
    dockerCommand: taskiq worker app.core.tkq:broker app.main:app
