"""add_token_version_and_refresh_token_table

Revision ID: 85fb0ade5ba1
Revises: 000105cdc4c1
Create Date: 2026-05-04 10:33:40.739824+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fb0ade5ba1'
down_revision = '000105cdc4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_status_logs_application_id'), 'application_status_logs', ['application_id'], unique=False)
    op.drop_constraint(op.f('companies_slug_key'), 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.drop_constraint(op.f('jobs_apply_code_key'), 'jobs', type_='unique')
    op.create_index(op.f('ix_jobs_apply_code'), 'jobs', ['apply_code'], unique=True)
    op.drop_constraint(op.f('tickets_code_key'), 'tickets', type_='unique')
    op.drop_index(op.f('ix_tickets_code'), table_name='tickets')
    op.create_index(op.f('ix_tickets_code'), 'tickets', ['code'], unique=True)
    op.create_unique_constraint(None, 'tickets', ['application_id'])
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'token_version')
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_index(op.f('ix_tickets_code'), table_name='tickets')
    op.create_index(op.f('ix_tickets_code'), 'tickets', ['code'], unique=False)
    op.create_unique_constraint(op.f('tickets_code_key'), 'tickets', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_jobs_apply_code'), table_name='jobs')
    op.create_unique_constraint(op.f('jobs_apply_code_key'), 'jobs', ['apply_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=False)
    op.create_unique_constraint(op.f('companies_slug_key'), 'companies', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_application_status_logs_application_id'), table_name='application_status_logs')
    # ### end Alembic commands ###
