"""add_revoked_at_to_refresh_token

Revision ID: 1f2b09dda015
Revises: f57f72ae1e12
Create Date: 2026-05-09 06:55:16.450320+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2b09dda015'
down_revision = 'f57f72ae1e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked_at')
    # ### end Alembic commands ###
