"""Centralized audit action codes."""

LOGIN_FAILURE = "LOGIN_FAILURE"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
LOGOUT = "LOGOUT"

CREATE_HR_ACCOUNT = "CREATE_HR_ACCOUNT"
UPDATE_USER = "UPDATE_USER"
DELETE_USER = "DELETE_USER"

CREATE_COMPANY = "CREATE_COMPANY"
UPDATE_COMPANY = "UPDATE_COMPANY"
COMPANY_SUSPEND = "COMPANY_SUSPEND"
COMPANY_ACTIVATE = "COMPANY_ACTIVATE"

JOB_CREATE = "JOB_CREATE"
JOB_REQUIREMENTS_UPDATE = "JOB_REQUIREMENTS_UPDATE"
JOB_FORM_UPDATE = "JOB_FORM_UPDATE"
JOB_PUBLISH = "JOB_PUBLISH"
JOB_CLOSE = "JOB_CLOSE"

JOB_FORM_FIELD_CREATE = "JOB_FORM_FIELD_CREATE"
JOB_FORM_FIELD_UPDATE = "JOB_FORM_FIELD_UPDATE"
JOB_FORM_FIELD_DELETE = "JOB_FORM_FIELD_DELETE"
JOB_FORM_FIELD_REORDER = "JOB_FORM_FIELD_REORDER"

APPLICATION_SUBMIT = "APPLICATION_SUBMIT"
APPLICATION_STATUS_UPDATE = "APPLICATION_STATUS_UPDATE"

INTERVIEW_SCHEDULE = "INTERVIEW_SCHEDULE"

SCORING_TEMPLATE_CREATE = "SCORING_TEMPLATE_CREATE"
SCORING_TEMPLATE_UPDATE = "SCORING_TEMPLATE_UPDATE"

AUTOMATED_SCREENING_CREATE = "AUTOMATED_SCREENING_CREATE"
AUTOMATED_SCREENING_UPDATE = "AUTOMATED_SCREENING_UPDATE"
AUTOMATED_SCREENING_FALLBACK = "AUTOMATED_SCREENING_FALLBACK"
MANUAL_OVERRIDE_SCORE = "MANUAL_OVERRIDE_SCORE"

NOTIFICATION_MARK_READ = "NOTIFICATION_MARK_READ"
NOTIFICATION_MARK_READ_ALL = "NOTIFICATION_MARK_READ_ALL"
NOTIFICATION_CREATE = "NOTIFICATION_CREATE"
