"""Error message constants."""

ERR_INVALID_CREDENTIALS = "Email atau password salah."
ERR_USER_NOT_FOUND = "Pengguna tidak ditemukan."
ERR_UNAUTHORIZED = "Akses tidak diizinkan."
ERR_FORBIDDEN = "Terlarang — izin tidak memadai."
ERR_COMPANY_SUSPENDED = "Akun perusahaan ditangguhkan."
ERR_DUPLICATE_APPLICATION = "Anda sudah melamar untuk lowongan ini."
ERR_MISSING_DOCUMENTS = "Dokumen wajib belum diunggah."
ERR_JOB_NOT_FOUND = "Lowongan tidak ditemukan."
ERR_APPLICATION_NOT_FOUND = "Lamaran tidak ditemukan."
ERR_TICKET_NOT_FOUND = "Tiket tidak ditemukan."
ERR_FILE_TOO_LARGE = "Ukuran file melebihi batas maksimal."
ERR_INVALID_FILE_TYPE = "Format file tidak didukung."
ERR_KNOCKOUT_FAIL = "Lamaran tidak memenuhi kriteria wajib."
ERR_AI_UNAVAILABLE = "Layanan AI sedang tidak tersedia."
ERR_OCR_FAILED = "Gagal mengekstrak teks dari dokumen."
ERR_SCORING_TEMPLATE_MISSING = "Template penilaian belum dikonfigurasi untuk lowongan ini."
