"""Error message constants."""

ERR_INVALID_CREDENTIALS = "Invalid email or password."
ERR_USER_NOT_FOUND = "User not found."
ERR_UNAUTHORIZED = "Unauthorized access."
ERR_FORBIDDEN = "Forbidden — insufficient permissions."
ERR_COMPANY_SUSPENDED = "Company account is suspended."
ERR_DUPLICATE_APPLICATION = "You have already applied for this job."
ERR_MISSING_DOCUMENTS = "Required documents are missing."
ERR_JOB_NOT_FOUND = "Job vacancy not found."
ERR_APPLICATION_NOT_FOUND = "Application not found."
ERR_TICKET_NOT_FOUND = "Ticket not found."
ERR_FILE_TOO_LARGE = "File size exceeds maximum allowed."
ERR_INVALID_FILE_TYPE = "Invalid file type."
ERR_KNOCKOUT_FAIL = "Application does not meet mandatory requirements."
ERR_AI_UNAVAILABLE = "AI service is temporarily unavailable."
ERR_OCR_FAILED = "Failed to extract text from document."
ERR_SCORING_TEMPLATE_MISSING = "Scoring template not configured for this job."
