"""Screening runtime defaults and quota guards."""

DEFAULT_SCREENING_BATCH_MAX_PER_RUN = 5
DEFAULT_SCREENING_MANUAL_MAX_PARALLEL = 1
DEFAULT_SCREENING_MAX_PARALLEL_TOTAL = 2
DEFAULT_SCREENING_MAX_PER_HOUR = 20
DEFAULT_SCREENING_MAX_PER_DAY = 100
DEFAULT_SCREENING_STALE_TIMEOUT_HOURS = 2
DEFAULT_SCREENING_RECOVERY_RETRY_LIMIT = 2
DEFAULT_SCREENING_ENQUEUE_COOLDOWN_SECONDS = 900
DEFAULT_SCREENING_BATCH_ENQUEUE_DELAY_SECONDS = 3
DEFAULT_SCREENING_PROCESSING_LOCK_SECONDS = 7200
